name: Auto Merge

on:
  workflow_dispatch:
  push:
    branches:
      - feature/bugfix
    paths:
      - 'VERSION'

jobs:

jobs:
  merge-master-to-stg-to-dev:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M')"

    - name: Set Git config
      id: config
      run: |
          git config --local user.email "data.operations@dojo.tech"
          git config --local user.name "Data Operations"
    - name: Merge master back to staging
      id: m2s
      run: |
          git fetch
          git checkout master
          git pull origin master
          git checkout staging
          git pull origin staging
          echo "Auto-merge master back to staging [skip ci] - ${{ steps.date.outputs.date }}"

    - name: Merge staging back to develop
      id: s2d
      run: |
          git fetch
          git checkout staging
          git pull origin staging
          git checkout develop
          git pull origin develop
          echo "Auto-merge staging back to develop [skip ci] - ${{ steps.date.outputs.date }}"
