name: Auto Merge
on:
  pull_request:
    branches: master
    types:
      - closed

jobs:
  merge-master-to-stg-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "data.operations@dojo.tech"
          git config --local user.name "Data Operations"
    - name: Merge master back to staging
      run: |
          git fetch
          git checkout master
          git pull origin master
          git checkout staging
          git pull origin staging
          git merge master --ff -m "Auto-merge master back to staging"
          git push -u origin HEAD
          git status

    - name: Merge staging back to develop
      run: |
          git fetch
          git checkout staging
          git pull origin staging
          git checkout develop
          git pull origin develop
          git merge staging --ff -m "Auto-merge staging back to develop"
          git push -u origin HEAD
          git status
